using System;
using System.Net;
using System.Threading.Tasks;
using Aivora.Repositories.Enums;
using Aivora.Tests.ApiContract;
using FluentAssertions;
using Xunit;

namespace Aivora.Tests.IntegrationTests
{
    /// <summary>
    /// End-to-end HTTP tests for [Authorize(Policy = AdminPolicy)] endpoints, using real
    /// JWTs generated by ApiContractTestFactory (no placeholder tokens, no live-server dependency).
    /// Covers admin dashboard (stats) and dispute resolve/request-evidence per issue #148.
    /// </summary>
    public class AdminAuthorizationTests : IClassFixture<ApiContractTestFactory>
    {
        private readonly ApiContractTestFactory _factory;

        public AdminAuthorizationTests(ApiContractTestFactory factory)
        {
            _factory = factory;
            _factory.SeedDatabase();
        }

        [Fact]
        public async Task GetStats_Anonymous_ReturnsUnauthorized()
        {
            var client = new ApiContractClient(_factory.CreateUnauthenticatedClient());
            var (response, _) = await client.GetAsync("/api/v1/admin/stats");
            response.StatusCode.Should().Be(HttpStatusCode.Unauthorized);
        }

        [Fact]
        public async Task GetStats_AsNonAdmin_ReturnsForbidden()
        {
            var client = new ApiContractClient(_factory.CreateAuthenticatedClient(UserRole.CLIENT));
            var (response, _) = await client.GetAsync("/api/v1/admin/stats");
            response.StatusCode.Should().Be(HttpStatusCode.Forbidden);
        }

        [Fact]
        public async Task GetStats_AsAdmin_ReturnsOk()
        {
            var client = new ApiContractClient(_factory.CreateAuthenticatedClient(UserRole.ADMIN));
            var (response, _) = await client.GetAsync("/api/v1/admin/stats");
            response.StatusCode.Should().Be(HttpStatusCode.OK);
        }

        [Fact]
        public async Task ResolveDispute_AsNonAdmin_ReturnsForbidden()
        {
            var disputeId = await CreateFundedDisputeAsync();
            var client = new ApiContractClient(_factory.CreateAuthenticatedClient(UserRole.CLIENT));
            var (response, _) = await client.PutAsync($"/api/v1/disputes/{disputeId}/resolve",
                new { resolutionNote = "Attempted by non-admin" });
            response.StatusCode.Should().Be(HttpStatusCode.Forbidden);
        }

        [Fact]
        public async Task ResolveDispute_AsAdmin_ReturnsOk()
        {
            var disputeId = await CreateFundedDisputeAsync();
            var client = new ApiContractClient(_factory.CreateAuthenticatedClient(UserRole.ADMIN));
            var (response, body) = await client.PutAsync($"/api/v1/disputes/{disputeId}/resolve",
                new { resolutionNote = "Resolved via admin authorization test." });
            response.StatusCode.Should().Be(HttpStatusCode.OK);
            body!.Value.GetProperty("data").GetProperty("status").GetString().Should().Be("RESOLVED");
        }

        [Fact]
        public async Task GetProject_AsAdmin_ReturnsOk()
        {
            var (_, projectId) = await CreateFundedProjectAsync();
            var client = new ApiContractClient(_factory.CreateAuthenticatedClient(UserRole.ADMIN));
            var (response, body) = await client.GetAsync($"/api/v1/projects/{projectId}");
            response.StatusCode.Should().Be(HttpStatusCode.OK);
            body!.Value.GetProperty("data").GetProperty("id").GetString().Should().Be(projectId.ToString());
        }

        [Fact]
        public async Task RequestEvidence_AsNonAdmin_ReturnsForbidden()
        {
            var disputeId = await CreateFundedDisputeAsync();
            var client = new ApiContractClient(_factory.CreateAuthenticatedClient(UserRole.EXPERT));
            var (response, _) = await client.PutAsync($"/api/v1/disputes/{disputeId}/request-evidence",
                new { note = "Attempted by non-admin" });
            response.StatusCode.Should().Be(HttpStatusCode.Forbidden);
        }

        [Fact]
        public async Task RequestEvidence_AsAdmin_ReturnsOk()
        {
            var disputeId = await CreateFundedDisputeAsync();
            var client = new ApiContractClient(_factory.CreateAuthenticatedClient(UserRole.ADMIN));
            var (response, _) = await client.PutAsync($"/api/v1/disputes/{disputeId}/request-evidence",
                new { note = "Please provide more evidence." });
            response.StatusCode.Should().Be(HttpStatusCode.OK);
        }

        /// <summary>
        /// Runs job -> proposal -> accept -> fund -> deliverable so each test has a fresh
        /// funded milestone (and its project) to act on. Returns (milestoneId, projectId).
        /// </summary>
        private async Task<(Guid MilestoneId, Guid ProjectId)> CreateFundedProjectAsync()
        {
            var clientClient = new ApiContractClient(_factory.CreateAuthenticatedClient(UserRole.CLIENT));
            var createJobReq = new
            {
                title = $"Admin Authz Test Job {Guid.NewGuid()}",
                originalDescription = "Job for admin authorization test coverage",
                categoryId = ApiContractTestData.CategoryId,
                budgetType = "FIXED",
                budgetMin = 500,
                budgetMax = 500,
                currency = "AICOIN",
                timelineDays = 14,
                visibility = "PUBLIC",
                skillIds = new System.Collections.Generic.List<Guid> { ApiContractTestData.SkillId }
            };
            var (_, jobBody) = await clientClient.PostAsync("/api/v1/jobs", createJobReq);
            var jobId = Guid.Parse(jobBody!.Value.GetProperty("data").GetProperty("id").GetString()!);
            await clientClient.PostAsync($"/api/v1/jobs/{jobId}/publish", new { });

            var expertClient = new ApiContractClient(_factory.CreateAuthenticatedClient(UserRole.EXPERT));
            var createProposalReq = new
            {
                jobId,
                coverLetter = "Proposal for admin authz test.",
                proposedBudget = 500,
                proposedTimelineDays = 10,
                milestones = new System.Collections.Generic.List<object>
                {
                    new { title = "Admin Authz M1", description = "Deliverable 1", amount = 500, dueDays = 5, orderIndex = 1, acceptanceCriteria = "Criteria 1" }
                }
            };
            var (_, propBody) = await expertClient.PostAsync($"/api/v1/jobs/{jobId}/proposals", createProposalReq);
            var proposalId = Guid.Parse(propBody!.Value.GetProperty("data").GetProperty("id").GetString()!);

            var (_, accBody) = await clientClient.PutEmptyAsync($"/api/v1/proposals/{proposalId}/accept");
            var projectId = Guid.Parse(accBody!.Value.GetProperty("data").GetProperty("projectId").GetString()!);

            var (_, getProjBody) = await clientClient.GetAsync($"/api/v1/projects/{projectId}");
            var milestoneId = Guid.Parse(getProjBody!.Value.GetProperty("data").GetProperty("milestones")[0].GetProperty("id").GetString()!);

            await clientClient.PutEmptyAsync($"/api/v1/milestones/{milestoneId}/fund");

            await expertClient.PostAsync($"/api/v1/milestones/{milestoneId}/deliverables",
                new { description = "Initial delivery for admin authz test", note = "Please review" });

            return (milestoneId, projectId);
        }

        /// <summary>
        /// Extends CreateFundedProjectAsync with an OPEN dispute so each authz test has its
        /// own fresh dispute to act on.
        /// </summary>
        private async Task<Guid> CreateFundedDisputeAsync()
        {
            var (milestoneId, _) = await CreateFundedProjectAsync();
            var clientClient = new ApiContractClient(_factory.CreateAuthenticatedClient(UserRole.CLIENT));

            var (_, openDisBody) = await clientClient.PostAsync("/api/v1/disputes", new
            {
                milestoneId,
                reason = "Quality of work is poor",
                description = "Detailed explanation for admin authorization test."
            });
            return Guid.Parse(openDisBody!.Value.GetProperty("data").GetProperty("id").GetString()!);
        }
    }
}
